name = "sceall"
version = "1.0.0"
description = "Spawn OS processes and stream their stdio using BEAM ports!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "sceall" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
